//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Code_Clienta { get; set; }
        public string Passport_Data { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Adress { get; set; }
        public string e_mail { get; set; }
        public string Password { get; set; }
        public Nullable<int> id_zakaza { get; set; }
    
        public virtual zakazy zakazy { get; set; }
    }
}
