//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prods
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string code { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> id_zakazy { get; set; }
    
        public virtual zakazy zakazy { get; set; }
    }
}
