//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakazy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zakazy()
        {
            this.clients = new HashSet<client>();
            this.prodss = new HashSet<prods>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> code_client { get; set; }
        public string prods { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_of_closing { get; set; }
        public string time_prokat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prods> prodss { get; set; }
    }
}
